name: CI Pipeline

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # 1. Configurar el repositorio
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Configurar Docker
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # 3. Crear red para Docker Compose
      - name: Set up Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      # 4. Construir y ejecutar los contenedores
      - name: Build and start Docker Compose
        run: docker-compose up --build -d

      # 5. Esperar a que el backend esté listo
      - name: Wait for Backend to be Ready
        run: |
          sleep 10 # Tiempo para inicializar el backend
          docker logs server

      # 6. Ejecutar pruebas del backend
      - name: Run Backend Tests
        run: docker exec server npm test

      # 7. Detener y limpiar contenedores
      - name: Tear Down
        if: always()
        run: docker-compose down
